==========	IB Characteristics    ===========================
5		Delta f.(1-phi1*,2-phi2*,3-phi3*,4-phi4*,5-phi3,6-phi4)
0		Multi-Direct Forcing steps
7         	nIBMs(# of Immersed Bs)
========= IB #1 ============
3			Shape: 1=Square,2=Cylinder,3=Cube,4=Sphere,5-File,6-PipeFlow
F                 Drag Force
0	0.0	0.	Length:1-Infinite; 0-finite,zini,zend
0.15	0.10	0.0125	Centre:Cx,Cy,Cz
0.025			Radius
0			cmax: Number of marker layers
-1			Axis of extrusion (1-x, 2-y, 3-z, -1-none)
'tetrahedra.xyz'		File from where load the points.
F			Movement. F=steady; T= Rotating
F			Flow type (F:ext,T:int(pipe flow))
1.00 1		Reduction factor,refinement
---- Turbine application ---
2			Axis turbine type:1-Vertical, 2-Horizontal
0.2	0.0	0.0	Gravity centre of hydrofoils (VA)
0.0		 	Pitch Angle of hydrofoils(VA)
1		 	Number of hydrofoils wanted (1 to 4)(VA)
6.00			Rotational velocity (rad/s)
F			F-Fixed Rotation, T-Self-starting/FSI
3.0			Release time(s) to iniciate the self-starting
========= IB #2 ============
3			Shape: 1=Square,2=Cylinder,3=Cube,4=Sphere,5-File,6-PipeFlow
F                 Drag Force
0	0.0	0.	Length:1-Infinite; 0-finite,zini,zend
0.15	0.15	0.0125	Centre:Cx,Cy,Cz
0.025			Radius
0			cmax: Number of marker layers
-1			Axis of extrusion (1-x, 2-y, 3-z, -1-none)
'tetrahedra.xyz'		File from where load the points.
F			Movement. F=steady; T= Rotating
F			Flow type (F:ext,T:int(pipe flow))
1.00 1		Reduction factor,refinement
---- Turbine application ---
2			Axis turbine type:1-Vertical, 2-Horizontal
0.2	0.0	0.0	Gravity centre of hydrofoils (VA)
0.0		 	Pitch Angle of hydrofoils(VA)
1		 	Number of hydrofoils wanted (1 to 4)(VA)
6.00			Rotational velocity (rad/s)
F			F-Fixed Rotation, T-Self-starting/FSI
3.0			Release time(s) to iniciate the self-starting
========= IB #3 ============
3			Shape: 1=Square,2=Cylinder,3=Cube,4=Sphere,5-File,6-PipeFlow
F                 Drag Force
0	0.0	0.	Length:1-Infinite; 0-finite,zini,zend
0.45	0.175	0.0125	Centre:Cx,Cy,Cz
0.025			Radius
0			cmax: Number of marker layers
-1			Axis of extrusion (1-x, 2-y, 3-z, -1-none)
'tetrahedra.xyz'		File from where load the points.
F			Movement. F=steady; T= Rotating
F			Flow type (F:ext,T:int(pipe flow))
1.00 1		Reduction factor,refinement
---- Turbine application ---
2			Axis turbine type:1-Vertical, 2-Horizontal
0.2	0.0	0.0	Gravity centre of hydrofoils (VA)
0.0		 	Pitch Angle of hydrofoils(VA)
1		 	Number of hydrofoils wanted (1 to 4)(VA)
6.00			Rotational velocity (rad/s)
F			F-Fixed Rotation, T-Self-starting/FSI
3.0			Release time(s) to iniciate the self-starting
========= IB #4 ============
3			Shape: 1=Square,2=Cylinder,3=Cube,4=Sphere,5-File,6-PipeFlow
F                 Drag Force
0	0.0	0.	Length:1-Infinite; 0-finite,zini,zend
0.6	0.075	0.0125	Centre:Cx,Cy,Cz
0.025			Radius
0			cmax: Number of marker layers
-1			Axis of extrusion (1-x, 2-y, 3-z, -1-none)
'tetrahedra.xyz'		File from where load the points.
F			Movement. F=steady; T= Rotating
F			Flow type (F:ext,T:int(pipe flow))
1.00 1		Reduction factor,refinement
---- Turbine application ---
2			Axis turbine type:1-Vertical, 2-Horizontal
0.2	0.0	0.0	Gravity centre of hydrofoils (VA)
0.0		 	Pitch Angle of hydrofoils(VA)
1		 	Number of hydrofoils wanted (1 to 4)(VA)
6.00			Rotational velocity (rad/s)
F			F-Fixed Rotation, T-Self-starting/FSI
3.0			Release time(s) to iniciate the self-starting
========= IB #5 ============
2			Shape: 1=Square,2=Cylinder,3=Cube,4=Sphere,5-File,6-PipeFlow
F                 Drag Force
0	0.0	0.	Length:1-Infinite; 0-finite,zini,zend
0.4	0.125	0.0125	Centre:Cx,Cy,Cz
0.025			Radius
0			cmax: Number of marker layers
-1			Axis of extrusion (1-x, 2-y, 3-z, -1-none)
'tetrahedra.xyz'		File from where load the points.
F			Movement. F=steady; T= Rotating
F			Flow type (F:ext,T:int(pipe flow))
1.00 1		Reduction factor,refinement
---- Turbine application ---
2			Axis turbine type:1-Vertical, 2-Horizontal
0.2	0.0	0.0	Gravity centre of hydrofoils (VA)
0.0		 	Pitch Angle of hydrofoils(VA)
1		 	Number of hydrofoils wanted (1 to 4)(VA)
6.00			Rotational velocity (rad/s)
F			F-Fixed Rotation, T-Self-starting/FSI
3.0			Release time(s) to iniciate the self-starting
========= IB #6 ============
2			Shape: 1=Square,2=Cylinder,3=Cube,4=Sphere,5-File,6-PipeFlow
F                 Drag Force
0	0.0	0.	Length:1-Infinite; 0-finite,zini,zend
0.8	0.22	0.0125	Centre:Cx,Cy,Cz
0.025			Radius
0			cmax: Number of marker layers
-1			Axis of extrusion (1-x, 2-y, 3-z, -1-none)
'tetrahedra.xyz'		File from where load the points.
F			Movement. F=steady; T= Rotating
F			Flow type (F:ext,T:int(pipe flow))
1.00 1		Reduction factor,refinement
---- Turbine application ---
2			Axis turbine type:1-Vertical, 2-Horizontal
0.2	0.0	0.0	Gravity centre of hydrofoils (VA)
0.0		 	Pitch Angle of hydrofoils(VA)
1		 	Number of hydrofoils wanted (1 to 4)(VA)
6.00			Rotational velocity (rad/s)
F			F-Fixed Rotation, T-Self-starting/FSI
3.0			Release time(s) to iniciate the self-starting
========= IB #7 ============
4			Shape: 1=Square,2=Cylinder,3=Cube,4=Sphere,5-File,6-PipeFlow
F                 Drag Force
0	0.0	0.	Length:1-Infinite; 0-finite,zini,zend
0.5	0.19	0.0125	Centre:Cx,Cy,Cz
0.025			Radius
0			cmax: Number of marker layers
-1			Axis of extrusion (1-x, 2-y, 3-z, -1-none)
'tetrahedra.xyz'		File from where load the points.
F			Movement. F=steady; T= Rotating
F			Flow type (F:ext,T:int(pipe flow))
1.00 1		Reduction factor,refinement
---- Turbine application ---
2			Axis turbine type:1-Vertical, 2-Horizontal
0.2	0.0	0.0	Gravity centre of hydrofoils (VA)
0.0		 	Pitch Angle of hydrofoils(VA)
1		 	Number of hydrofoils wanted (1 to 4)(VA)
6.00			Rotational velocity (rad/s)
F			F-Fixed Rotation, T-Self-starting/FSI
3.0			Release time(s) to iniciate the self-starting