=======================Numerical parameters===============================
column 0.1 		     		 Keyword, Ubulk
0.004 0.003125 0.003125 	 dx,dy,dz
1000 1.d-6 7.0 0.6 0.000207    dens, kinematic visc, Pr, turb Schmidt, beta
0.0 0.0 -9.81              	 gx,gy,gz
3                            convection_scheme(1=Exp.Euler,2=AdamsBashfort,3=RK2,4=RK3)
3                            diffusion_scheme(1=Imp.Euler,2=CrankNicholson,3=ExplicitRungeKuttaDiff)
1                            differencing(1=2ndCDS,2=4thCDS,3=WENO)
2                            solver(1=sip,2=mg)
1 2                          multigrid step (ngrid), multigrid iteration scheme(1=GSS,2=TDMA,3=RBGSS)
30 2 1                       multigrid maximum iteration per time step,restriction iter, prolongation iter
0.005 F 25 0.2               dt,variable(T)/fixed(F) dt,sweeps,safety_factor
6000 F F 6000               itime_end,restart,reinitmean,n_out
T 100                       LTRANSIENT, results output
20 1.0E-5 5 5 5 20           niter,eps,nswp(1),nswp(2),nswp(3),nswp(4)
=======================Flow boundary conditions=========================
4			           West   Boundary Condition (1= Inflow; 12=1/7th power law; 7=prescribed inflow; 8=SEM)
4                            East   Boundary Condition (2= Outflow, 2=NeumannBC(NBC) 21= ConvectiveBC(CBC))
4                            South  Boundary Condition (3= Slip Condition)
4                            North  Boundary Condition (4= No-Slip Condition)
4                            Bottom Boundary Condition (5= Periodic Condition)
4                            Top    Boundary Condition (61=smooth log law; 62=rough log law; 63=1/6th law; 64=1/7th law; 65=1/8th law)
n 0.03			     Friction coefficient ('n':manning;'k':equivalent sand; only if bc=62)
F 5000			     save inflow data (precursor sim.) ; number of inlets
=======================Synthetic Eddy Method=======================
12					Velocity profile:1=Uniform; 12=1/7th PL
0.1					Turbulence intensity
1000					Number inlet profiles
=======================Modelling Options==========================
F 0.04 0.05 0.0                time_averaging,t_start_averaging1,t_start_averaging2,noise
T 1                          SGS-model,1=Smagorinsky,2=WALE,3=OneEqnModel,4=k-eps model (RANS)
2 2                          LMR (1=old ghost cell approach, 2=new ghost cell aplsproach),normal ghost velocity interpolation(1=2nd-order,2=4th-order)
F F F                        LIMB,LENERGY,LROUGH
F F, F   		           LPT, LSM, L_LSMbase
T T T                        LSCALAR,LActiveScalar,LNonNewt
2                            pl_ex (# of extra ghost planes. pl_ex=0 -> blocks have only 1 ghost layer)
301.11  298.57                    Th,Tc
=======================Energy boundary conditions=======================
7			     	     West   Energy BC (5= Periodic)
7                            East   Energy BC (7= Adiabatic)
7                            South  Energy BC (8= Cold Surface)
7                            North  Energy BC (9= Hot Surface)
7                            Bottom Energy BC
7                            Top    Energy BC
=======================Time series======================================
0				     num of time series points
0	12	22	22	point #1
