name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [fusion-forests-project]
  push:
    branches: [fusion-forests-project]


permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: fortran-lang/setup-fpm@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          sudo apt-get install -y openmpi-bin libopenmpi-dev

      - run: |
          cmake -S ./json-fortran/ -B ./build_json_fortran/ -DCMAKE_Fortran_COMPILER=mpif90
          cmake --build build_json_fortran
          cmake -S ./test-drive/ -B ./build_test_drive/ -DCMAKE_Fortran_COMPILER=mpif90
          cmake --build build_test_drive
          make -j $(nproc --all)
