name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [fusion-forests-project]
  push:
    branches: [fusion-forests-project]


permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - { compiler: gcc, version: 14, hdf5: On, json: On, coverage: On }
          - { compiler: gcc, version: 14, hdf5: Off, json: On }
          - { compiler: gcc, version: 14, hdf5: On, json: Off }
          - { compiler: gcc, version: 14, hdf5: Off, json: Off }
          # Disable nvfortran jobs for now to save on limited Github runner minutes
          #- { compiler: nvidia-hpc, version: '25.1', hdf5: On, json: On }
          #- { compiler: nvidia-hpc, version: '25.1', hdf5: Off, json: On }
          #- { compiler: nvidia-hpc, version: '25.1', hdf5: On, json: Off }
          #- { compiler: nvidia-hpc, version: '25.1', hdf5: Off, json: Off }

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: 'true'

      - run: |
          # Frees up space, so can install nvhpc.
          # See https://github.com/orgs/community/discussions/25678 for
          # where suggestion came from
          rm -rf /opt/hostedtoolcache

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

        
      - run: |
          sudo apt-get install -y openmpi-bin libopenmpi-dev
        if: ${{ contains(matrix.toolchain.compiler, 'gcc') }}

      - name: Modify makefile to switch off JSON
        if: ${{ contains(matrix.toolchain.json , 'Off') }}
        run: |
          sed -i 's/USE_JSON=1/USE_JSON=0/' makefile

      - name: Modify makefile to switch off HDF5
        if: ${{ contains(matrix.toolchain.hdf5 , 'Off') }}
        run: |
          sed -i 's/USE_HDF5=1/USE_HDF5=0/' makefile

      - name: Set number of threads to 1 for hdf5 tests
        if: ${{ contains(matrix.toolchain.hdf5, 'On') }}
        run: |
          # Just use single thread for tests when using HDF5
          echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV

      - run: |
          cmake -S ./json-fortran/ -B ./build_json_fortran/ -DCMAKE_Fortran_COMPILER=mpif90
          cmake --build build_json_fortran --parallel $(nproc --all)
          cmake -S ./test-drive/ -B ./build_test_drive/ -DCMAKE_Fortran_COMPILER=mpif90
          cmake --build build_test_drive --parallel $(nproc --all)
          cmake -S ./hdf5/ -B ./build_hdf5/ -DCMAKE_Fortran_COMPILER=mpif90 -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DHDF5_BUILD_FORTRAN=ON
          cmake --build build_hdf5 --parallel $(nproc --all)
          make -j $(nproc --all)

      - name: Setup LCOV
        if: ${{ contains(matrix.toolchain.coverage, 'On')   }}
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Remove folders from coverage report
        if: ${{ contains(matrix.toolchain.coverage, 'On')}}
        run: |
          lcov --directory . --capture --output-file coverage.info --gcov-tool gcov
          lcov --remove coverage.info "$PWD/tests/*" --output-file coverage.info

      - name: Report code coverage as comment
        if: ${{ contains(matrix.toolchain.coverage, 'On') }}
        uses: zgosalvez/github-actions-report-lcov@v7
        with:
          coverage-files: coverage.info
          minimum-coverage: 0
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: src
          update-comment: true
